### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by minexew** [Byzantian/TempleOS-V#3]
Before any code is written, we need to agree on a license.

In my view, we should honor the legacy of TempleOS by sticking to its 100% public domain model.

BSD/MIT/WTFPL/... would probably be fine as well. But the GPL is pretty restrictive and perhaps needlessly opinionated about what people should or should not be allowed to do. If somebody wants to build a fucking TempleV toaster, they shouldn't be forced to give you JTAG access

**Comment by Byzantian** [comment]
I completely agree. I'm not a GPL warrior of any sort. Just set it to GPL3 as a sort of joke or failsafe at first. After all, nobody is ever going to fork this for a commercial closed source project. As far as I know the only difference between public domain and MIT is having to credit the original authors, right? Which one do you prefer?

**Comment by minexew** [comment]
I vote for public domain.

**Comment by Byzantian** [comment]
So, public domain it is. Should I just delete the license file or what?
